apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: tum-campus-app
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ join "`) || Host(`" $.Values.urls.v1 }}`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: redirect-to-new-backend
    - kind: Rule
      match: Host(`{{ join "`) || Host(`" $.Values.urls.v2 }}`)
      middlewares:
        - name: cors
      services:
        - name: backend-svc
          port: 50051
    - kind: Rule
      match: Host(`{{ join "`) || Host(`" $.Values.urls.v2WebGrpc }}`)
      middlewares:
        - name: cors
      services:
        - name: backend-svc
          port: 8081
    - kind: Rule
      match: (Host(`{{ join "`) || Host(`" $.Values.urls.v2 }}`)) && Headers(`Content-Type`, `application/grpc`)
      middlewares:
        - name: cors
      services:
        - name: backend-svc
          port: 50051
          scheme: h2c
  tls:
    secretName: app.tum.de
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-http
  labels:
    app.kubernetes.io/part-of: tum-campus-app
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ join "`) || Host(`" (concat $.Values.urls.v1 $.Values.urls.v2 $.Values.urls.v2WebGrpc) }}`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: https
