apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: tum-campus-app
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ join "|" $.Values.urls.v1 }}`)
      services:
        - name: backend-v1-svc
          port: 80
    - kind: Rule
      match: {{ join "|" $.Values.urls.v2 }}
      services:
        - name: backend-v2-svc
          port: 50051
  tls:
    secretName: app.tum.de
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-http
  labels:
    app.kubernetes.io/part-of: tum-campus-app
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: {{ join " || " (concat $.Values.urls.v1 $.Values.urls.v2) }}
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: https
