apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ $.Values.url }}`)
      services:
        - name: campus-backend-svc
          port: 50051
    - kind: Rule
      match: Host(`{{ $.Values.urlGrpc }}`)
      services:
        - name: campus-backend-svc
          port: 50051
  tls:
    secretName: {{ $.Values.url }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-http
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  namespace: {{ $.Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ $.Values.url }}`) || Host(`{{ $.Values.urlGrpc }}`)
      services:
        - name: noop@internal
          kind: TraefikService
      middlewares:
        - name: https
