ls:
  .dir: snake_case
  .pb.gw.go: snake_case
  .pb.go: snake_case
  .go: snake_case

ignore:
  - venv
  - server/swagger/node_modules
  - .idea
  - .git
  - .github
  - .vscode
  - apns_auth_key.p8
