services:
  backend:
    image: ghcr.io/tum-dev/campus-backend/backend-server:latest
    restart: always
    build:
      context: server/
      args:
        version: dev # compiled with the git sha in prod
    ports:
      - 50051:50051
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(db:${DB_PORT:-3306})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - ENVIRONMENT=dev
      - SENTRY_DSN=${SENTRY_DSN}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_P8_FILE_PATH=${APNS_P8_FILE_PATH}
      - MensaCronDisabled=true
      - OMDB_API_KEY=${OMDB_API_KEY}
      - CAMPUS_API_TOKEN=${CAMPUS_API_TOKEN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_URL=${SMTP_URL:-postout.lrz.de}
      - SMTP_USERNAME=${SMTP_USERNAME:-tca-support.os.in@tum.de}
      - SMTP_PORT=${SMTP_PORT:-587}
    volumes:
      - backend-storage:/Storage
      - ./apns_auth_key.p8:${APNS_P8_FILE_PATH}
    user: 1000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: bitnami/mariadb:latest
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - campus-db-data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  # The following code can be used to test the envoy proxy locally
  # The reason why this is commented out is that this working requires the following change:
  #
  # ./deployment/charts/backend/files/envoy.yaml
  #   socket_address:
  # -   address: localhost
  # +   address: backend
  #     port_value: 50051
  #
  #grpc-web:
  #  image: envoyproxy/envoy:v1.27-latest
  #  restart: always
  #  command:
  #    - /docker-entrypoint.sh
  #    - --config-path
  #    - /etc/envoy/envoy.yaml
  #    - --service-cluster
  #    - backend-v2
  #    - --service-node
  #    - backend-v2
  #    - --log-level
  #    - info
  #  ports:
  #    - 8081:8081
  #    - 9901:9901
  #  volumes:
  #    - ./deployment/charts/backend/files/envoy.yaml:/etc/envoy/envoy.yaml
  #  depends_on:
  #    - backend

volumes:
  campus-db-data:
    driver: local
  backend-storage:
    driver: local
