services:
  backend-v2:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-v2.rule=Host(`api.tum.app`)"

      - "traefik.http.routers.backend-v2_h2.rule=Host(`api-grpc.tum.app`) && Headers(`Content-Type`, `application/grpc`)"
      - "traefik.http.routers.backend-v2_h2.scheme=h2c"
    expose:
      - "50051"
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(db:${DB_PORT:-3306})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - SENTRY_DSN=${SENTRY_DSN}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_P8_FILE_PATH=${APNS_P8_FILE_PATH}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - CAMPUS_API_TOKEN=${CAMPUS_API_TOKEN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_URL=${SMTP_URL:-postout.lrz.de}
      - SMTP_USERNAME=${SMTP_USERNAME:-bot@tum.app}
      - SMTP_FROM=${SMTP_FROM:-bot@tum.app}
      - SMTP_PORT=${SMTP_PORT:-587}
      - MensaCronDisabled=true
    volumes:
      - backend-storage:/Storage
      - ./apns_auth_key.p8:${APNS_P8_FILE_PATH}:ro
    user: 1000:3000
    read_only: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: bitnami/mariadb:latest
    restart: unless-stopped
    expose:
      - "${DB_PORT:-3306}"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - campus-db-data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  grpc-web:
    image: envoyproxy/envoy:v1.27-latest
    restart: always
    command:
      - /docker-entrypoint.sh
      - --config-path
      - /etc/envoy/envoy.yaml
      - --service-cluster
      - backend-v2
      - --service-node
      - backend-v2
      - --log-level
      - info
    expose:
      - "8081"
      #- "9901" # admin interface, not very useful
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-v2.rule=Host(`api.tum.app`)"
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - backend-v2
  backend-v1-accesslogs:
    image: alpine:1.36
    command: [ /bin/sh, -c, 'tail -n+1 -F /var/log/apache2/access.log' ]
    volumes:
      - legacybackend-logs:/var/log/:ro
    depends_on:
      - backend-v1
  backend-v1-errorlogs:
    image: alpine:1.36
    command: [ /bin/sh, -c, 'tail -n+1 -F /var/log/apache2/error.log' ]
    volumes:
      - legacybackend-logs:/var/log/:ro
    depends_on:
      - backend-v1
  backend-v1:
    image: ghcr.io/kordianbruck/tca-backend/tca-server:latest
    restart: always
    read_only: true
    tmpfs:
      - /app/Tmp/
      - /var/www/html/tmp/
      - /var/run/apache2/
    volumes:
      - legacybackend-logs:/var/log/
      - legacybackend-config:/app/Config/cfg.ini:ro
      - backend-storage:/app/Storage/
    expose:
      - "80"

volumes:
  campus-db-data:
    driver: local
  backend-storage:
    driver: local
  legacybackend-config:
    driver: local
  legacybackend-logs:
    driver: local
