services:
  backend:
    container_name: campus-backend
    image: ghcr.io/tum-dev/campus-backend/backend-server:latest
    restart: always
    build:
      context: server/
      args:
        version: dev # compiled with the git sha in prod
    ports:
      - 50051:50051
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(db:${DB_PORT:-3306})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - ENVIRONMENT=dev
      - SENTRY_DSN=${SENTRY_DSN}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_P8_FILE_PATH=${APNS_P8_FILE_PATH}
    volumes:
      - backend-storage:/Storage
      - ./apns_auth_key.p8:${APNS_P8_FILE_PATH}
    user: 1000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: campus-db
    image: bitnami/mariadb:latest
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - campus-db-data:/bitnami/mariadb
      - ./deployment/charts/backend/files/source-schema.sql:/docker-entrypoint-startdb.d/schema.sql
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  campus-db-data:
    driver: local
  backend-storage:
    driver: local