services:
  backend-v2:
    image: ghcr.io/tum-dev/campus-backend/backend-server:latest
    restart: always
    ports:
      - "50051:50051"
    environment:
      - DB_DSN=root:${DB_ROOT_PASSWORD}@tcp(db:${DB_PORT:-3306})/${DB_NAME}?charset=utf8mb4&parseTime=True&loc=Local
      - ENVIRONMENT=${ENVIRONMENT:-dev}
      - SENTRY_DSN=${SENTRY_DSN}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_P8_FILE_PATH=${APNS_P8_FILE_PATH}
      - OMDB_API_KEY=${OMDB_API_KEY}
      - CAMPUS_API_TOKEN=${CAMPUS_API_TOKEN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_URL=${SMTP_URL:-postout.lrz.de}
      - SMTP_USERNAME=${SMTP_USERNAME:-tca-support.os.in@tum.de}
      - SMTP_PORT=${SMTP_PORT:-587}
    volumes:
      - backend-storage:/Storage
      - ./apns_auth_key.p8:${APNS_P8_FILE_PATH}:ro
    user: 1000:3000
    read_only: true
    depends_on:
      db:
        condition: service_healthy
  db:
    image: bitnami/mariadb:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - campus-db-data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  campus-db-data:
    driver: local
  backend-storage:
    driver: local
