namespace: tca-backend
tag: latest
urls:
  v1:
  - app.tum.app
  - app.tum.de
  - www.app.tum.de
  - tumcabe.in.tum.de
  - tuinf01-tcabe.srv.mwn.de
  v2:
  - api.tum.app
  - api-grpc.tum.app

# see https://github.com/bitnami/charts/tree/main/bitnami/mariadb for more options, the se are just the most important ones
mariadb:
  enabled: true
  architecture: standalone
  auth:
    rootPassword: changeme-changeme-changeme
    username: backend
    password: changeme-changeme-changeme
    replicationPassword: changeme-changeme-changeme
    forcePassword: true
    database: tca
  primary:
    pdb:
      create: true
    persistence:
      size: 1Gi
      storageClass: local-path
      # storageClass: longhorn
  secondary:
    pdb:
      create: true
    persistence:
      size: 1Gi
      storageClass: local-path
      # storageClass: longhorn
  volumePermissions:
    enabled: true
  initdbScriptsConfigMap: sql-init


backend:
  sentry:
    dsn: changeme-changeme-changeme
  apns:
    auth_key: changeme-changeme-changeme
    key_id: changeme-changeme-changeme
    team_id: changeme-changeme-changeme
legacy:
  config: changeme-changeme-changeme
  imagepullsecret: changeme-changeme-changeme