name: campus-backend
description: Backend for the TUM campus apps
version: 1.0.0
apiVersion: v1
deprecated: false
icon: https://tum.sexy/favicon.png



dependencies:
  - condition: mariadbEnabled
    name: mariadb-galera
    repository: https://charts.bitnami.com/bitnami
    version: 10.x.x