{{- $db := $.Values.mariadb.auth -}}
{{- if $.Values.mariadb-galera.enabled -}}
  {{- $db = $.Values.mariadb-galera.db -}}
{{ end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tum-campus-app
      app.kubernetes.io/name: backend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: tum-campus-app
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: tca-backend
          image: ghcr.io/tum-dev/campus-backend/backend-server:{{ $.Values.tag }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: prod
            - name: APNS_P8_FILE_PATH
              value: /etc/apns_auth_key.p8
            - key: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: SENTRY_DSN
            - name: DB_DSN
              value: "{{ $db.username }}:{{ $db.password }}@tcp(mariadb.{{ $.Values.namespace }}.svc.cluster.local:3306)/{{ $db.database }}?charset=utf8mb4&parseTime=True&loc=Local"
            - key: APNS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_KEY_ID
            - name: APNS_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_TEAM_ID
          volumeMount:
            - name: backend-api-keys
              mountPath: /etc/apns_auth_key.p8
              subPath: apns_auth_key
              readOnly: true
          ports:
            - containerPort: 50051
              name: https
          securityContext:
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-api-keys
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
data:
  SENTRY_DSN: {{ $.Values.backend.SENTRY_DSN | b64enc | quote }}
  APNS_AUTH_KEY: {{ $.Values.backend.apns.auth_key | b64enc | quote }}
  APNS_KEY_ID: {{ $.Values.backend.apns.key_id | b64enc | quote }}
  APNS_TEAM_ID: {{ $.Values.backend.apns.team_id | b64enc | quote }}
