apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  namespace: {{ $.Values.namespace }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
