apiVersion: v1
kind: Service
metadata:
  name: campus-backend-svc
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend
  ports:
    - name: https
      port: 50051
      targetPort: 50051