{{- $db := $.Values.mariadb.auth -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend-v2
  namespace: {{ $.Values.namespace }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tum-campus-app
      app.kubernetes.io/name: backend-v2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: tum-campus-app
        app.kubernetes.io/name: backend-v2
    spec:
      priorityClassName: tca-backend
      volumes:
        - name: storage-vol
          persistentVolumeClaim:
            readOnly: false
            claimName: backend-pvc
        - name: backend-api-keys
          secret:
            secretName: backend-api-keys
        - name: backend-grpc-web-config
          configMap:
            name: backend-grpc-web-config
      containers:
        - name: tca-backend
          image: ghcr.io/tum-dev/campus-backend/backend-server:{{ $.Values.tag }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: prod
            - name: MensaCronDisabled
              value: "true"
            - name: APNS_P8_FILE_PATH
              value: /etc/apns_auth_key.p8
            - name: OMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: OMDB_API_KEY
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: SENTRY_DSN
            - name: CAMPUS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: CAMPUS_API_TOKEN
            - name: DB_DSN
              value: "{{ $db.username }}:{{ $db.password }}@tcp(tca-backend-mariadb.{{ $.Values.namespace }}.svc.cluster.local:3306)/{{ $db.database }}?charset=utf8mb4&parseTime=True&loc=Local"
            - name: APNS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_KEY_ID
            - name: APNS_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_TEAM_ID
          volumeMounts:
            - mountPath: /Storage/
              name: storage-vol
              readOnly: false
            - mountPath: /etc/apns_auth_key.p8
              subPath: apns_auth_key.p8
              name: backend-api-keys
              readOnly: true
          ports:
            - containerPort: 50051
              name: http
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 3000
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 5
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 60
            periodSeconds: 1
        - name: grpc-web-proxy
          image: envoyproxy/envoy:v1.27-latest
          imagePullPolicy: IfNotPresent
          args:
            - --config-path
            - /etc/envoy/envoy.yaml
            - --service-cluster
            - backend-v2
            - --service-node
            - backend-v2
            - --log-level
            - info
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 9901
              name: admin
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              name: backend-grpc-web-config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /ready
              port: admin
            failureThreshold: 5
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /ready
              port: admin
            failureThreshold: 60
            periodSeconds: 1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-api-keys
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend-v2
data:
  OMDB_API_KEY: {{ $.Values.backend.omdbApiKey | b64enc }}
  CAMPUS_API_TOKEN: {{ $.Values.backend.campusApiToken | b64enc }}
  SENTRY_DSN: {{ $.Values.backend.sentry.dsn | b64enc }}
  apns_auth_key.p8: {{ $.Values.backend.apns.auth_key }}
  APNS_KEY_ID: {{ $.Values.backend.apns.key_id | b64enc }}
  APNS_TEAM_ID: {{ $.Values.backend.apns.team_id | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-grpc-web-config
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend-v2
data:
  envoy.yaml: |-
{{ .Files.Get "files/envoy.yaml" | indent 4 }}
