{{ range $name := (list "backend-v1" "backend-v2") }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
    labels:
      app.kubernetes.io/part-of: tum-campus-app
      app.kubernetes.io/name: {{ $name }}
    namespace: {{ $.Values.namespace }}
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
{{ end }}