{{- $db := $.Values.mariadb.auth -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend-v2
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: tum-campus-apppus-app
      app.kubernetes.io/name: backend-v2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: tum-campus-apppus-app
        app.kubernetes.io/name: backend-v2
    spec:
      volumes:
        - name: storage-vol
          persistentVolumeClaim:
            readOnly: false
            claimName: backend-pvc
        - name: backend-api-keys
          secret:
            secretName: backend-api-keys
      containers:
        - name: tca-backend
          image: ghcr.io/tum-dev/campus-backend/backend-server:{{ $.Values.tag }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: prod
            - name: APNS_P8_FILE_PATH
              value: /etc/apns_auth_key.p8
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: SENTRY_DSN
            - name: DB_DSN
              value: "{{ $db.username }}:{{ $db.password }}@tcp(tca-backend-mariadb.{{ $.Values.namespace }}.svc.cluster.local:3306)/{{ $db.database }}?charset=utf8mb4&parseTime=True&loc=Local"
            - name: APNS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_KEY_ID
            - name: APNS_TEAM_ID
              valueFrom:
                secretKeyRef:
                  name: backend-api-keys
                  key: APNS_TEAM_ID
          volumeMounts:
            - mountPath: /app/Storage/
              name: storage-vol
              readOnly: false
            - mountPath: /etc/apns_auth_key.p8
              subPath: apns_auth_key.p8
              name: backend-api-keys
              readOnly: true
          ports:
            - containerPort: 50051
              name: http
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 1000m
              memory: 50Mi
            limits:
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 1
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 20
            periodSeconds: 1
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-api-keys
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    app.kubernetes.io/name: backend-v2
data:
  SENTRY_DSN: {{ $.Values.backend.sentry.dsn | b64enc }}
  apns_auth_key.p8: {{ $.Values.backend.apns.auth_key }}
  APNS_KEY_ID: {{ $.Values.backend.apns.key_id | b64enc }}
  APNS_TEAM_ID: {{ $.Values.backend.apns.team_id | b64enc }}
