apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/part-of: tum-campus-app
    type: longhorn
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
