name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint-server
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: server
      - name: golangci-lint-client
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: client
