name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: |
            server/go.sum
      - name: run tests
        run: go test -v ./...
        working-directory: ./server
  test_migrations:
    runs-on: ubuntu-latest
    services:
      auto_mariadb:
        image: bitnami/mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: super_secret_passw0rd
          MARIADB_DATABASE: campus_db
      manual_mariadb:
        image: bitnami/mariadb:latest
        ports:
          - 3300:3306
        env:
          MARIADB_ROOT_PASSWORD: super_secret_passw0rd
          MARIADB_DATABASE: campus_db
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: |
            server/go.sum
      - name: wait for db
        run: sleep 20
      - name: run manual migrations
        run: go run main.go
        working-directory: ./server
        env:
          CI_EXIT_AFTER_MIGRATION: "true"
          CI_AUTO_MIGRATION: "false"
          DB_DSN: root:super_secret_passw0rd@tcp(localhost:3306)/campus_db?charset=utf8mb4&parseTime=True&loc=Local
          ENVIRONMENT: dev
      - name: run auto migrations
        run: go run main.go
        working-directory: ./server
        env:
          CI_EXIT_AFTER_MIGRATION: "true"
          CI_AUTO_MIGRATION: "true"
          DB_DSN: root:super_secret_passw0rd@tcp(localhost:3300)/campus_db?charset=utf8mb4&parseTime=True&loc=Local
          ENVIRONMENT: dev
      - uses: ariga/setup-atlas@master
      - name: export diff the migrations
        run: atlas schema diff --from "maria://root:super_secret_passw0rd@tcp(localhost:3306)/campus_db?charset=utf8mb4&parseTime=True&loc=Local" --to "maria://root:super_secret_passw0rd@tcp(localhost:3300)/campus_db?charset=utf8mb4&parseTime=True&loc=Local"
  build:
    runs-on: ubuntu-latest
    needs: [test, test_migrations]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/tum-dev/campus-backend/backend-server
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=sha
        flavor: |
          latest=true
          prefix=
          suffix=
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: server
        pull: true
        push: ${{ github.event_name != 'pull_request' }}
        build-args: version=${{ github.sha }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
